import { storage } from "./storage";
import { db } from "./db";
import { communities } from "@shared/schema";
import { sql } from "drizzle-orm";

const SEED_COMMUNITIES = [
  {
    name: "Dancing Rabbit Ecovillage",
    slug: "dancing-rabbit-ecovillage",
    tagline: "A growing ecovillage creating a sustainable culture on regenerative land in rural Missouri",
    overview: "Dancing Rabbit Ecovillage is one of the most established intentional communities in the United States, located on 280 acres of rolling prairie in northeast Missouri. Founded in 1997, the community has grown into a vibrant experiment in sustainable living, with members committed to reducing their ecological footprint to 10% of the American average.\n\nThe community combines natural building techniques with solar energy systems and extensive permaculture gardens. Members share resources through a cooperative economic model while maintaining individual autonomy. Dancing Rabbit serves as both a living laboratory for sustainable technologies and an educational center, hosting thousands of visitors each year.",
    locationCountry: "United States",
    locationRegion: "Missouri",
    locationLat: 40.07,
    locationLng: -92.03,
    stage: "mature",
    population: 75,
    foundedYear: 1997,
    websiteUrl: "https://www.dancingrabbit.org",
    heroImageUrl: "/images/communities/dancing-rabbit.png",
    solarpunkScore: 78,
    scoreEnergy: 8.5,
    scoreLand: 8.0,
    scoreTech: 6.5,
    scoreGovernance: 8.0,
    scoreCommunity: 8.5,
    scoreCircularity: 7.0,
    techStack: { energy: ["Solar Panels", "Passive Solar Design"], water: ["Rainwater Harvesting", "Greywater Systems"], food: ["Permaculture Gardens", "Food Forest"], shelter: ["Strawbale Construction", "Cob Building", "Earthen Plaster"], digital: ["Community Wi-Fi", "Shared Computing"], governance: ["Consensus Decision-Making", "Village Council"] },
    communityLife: "Life at Dancing Rabbit revolves around ecological covenants that all members agree to follow. These include not owning personal vehicles, using only renewable energy, and organic land management. The community has a vibrant social scene with shared meals, work parties, and regular community meetings.\n\nMembers pursue diverse livelihoods including farming, building, education, and remote work. Children attend the community's unschooling cooperative, and the village maintains a robust visitor program for those interested in sustainable living.",
    howToJoin: "Dancing Rabbit welcomes visitors year-round through their visitor program. Prospective members typically visit for 1-3 weeks before applying for residency. The membership process involves a period of provisional membership (usually 6-12 months) followed by a community vote.\n\nThere are no buy-in requirements, but members need to secure housing either by building or purchasing an existing structure. The community offers land leases through their land trust.",
    landDescription: "The community sits on 280 acres of rolling Missouri prairie, featuring native grasslands, food forests, ponds, and extensively managed permaculture zones. The land includes both common areas and individual homesites, connected by walking paths and shared infrastructure.",
    aiConfidence: 0.95,
    sourcesCount: 12,
    isPublished: true,
    isFormingDisclaimer: false,
    tags: ["Permaculture", "Natural Building", "Solar Energy", "Consensus Governance", "Visitors Welcome", "Accepting Members"],
    links: [{ url: "https://www.dancingrabbit.org", title: "Official Website", type: "website" }],
  },
  {
    name: "Earthaven Ecovillage",
    slug: "earthaven-ecovillage",
    tagline: "A permaculture-based intentional community nestled in the Blue Ridge Mountains of North Carolina",
    overview: "Earthaven Ecovillage is a 329-acre intentional community in the mountains of western North Carolina, founded in 1994. The community is dedicated to demonstrating that a community-scale, ecologically sustainable human settlement can exist harmoniously within its local ecosystem.\n\nWith over 100 residents living in neighborhoods scattered across forested mountain terrain, Earthaven combines permaculture design with appropriate technology. The community generates its own power through micro-hydro and solar systems, manages its own water and waste, and grows a significant portion of its food on-site.",
    locationCountry: "United States",
    locationRegion: "North Carolina",
    locationLat: 35.38,
    locationLng: -82.57,
    stage: "mature",
    population: 100,
    foundedYear: 1994,
    websiteUrl: "https://www.earthaven.org",
    heroImageUrl: "/images/communities/earthaven.png",
    solarpunkScore: 82,
    scoreEnergy: 8.0,
    scoreLand: 9.0,
    scoreTech: 7.0,
    scoreGovernance: 8.5,
    scoreCommunity: 8.0,
    scoreCircularity: 8.5,
    techStack: { energy: ["Micro-Hydro", "Solar PV", "Passive Solar"], water: ["Spring-Fed Systems", "Constructed Wetlands", "Composting Toilets"], food: ["Permaculture Food Forest", "Market Garden", "Mushroom Cultivation"], shelter: ["Timber Frame", "Cob", "Living Roofs", "Earthen Construction"], digital: ["Mesh Network"], governance: ["Sociocracy", "Council Process"] },
    communityLife: "Earthaven operates on a model of neighborhood clusters, each with its own character and sub-governance. Community-wide decisions are made through a modified sociocratic process. Members participate in work exchanges, shared meals, and seasonal celebrations rooted in the rhythms of the land.\n\nThe community hosts several small businesses including a permaculture school, a café, and various craft workshops. Children are educated through a mix of homeschooling and the local public school.",
    howToJoin: "Earthaven has a structured path to membership that begins with attending an introductory weekend or longer visit. Prospective members then enter a candidacy period that typically lasts 9-18 months, during which they participate in community life and governance.\n\nMembership requires a site lease purchase (prices vary by neighborhood) and ongoing monthly dues. The community is selectively accepting new members.",
    landDescription: "329 acres of mountain forest in the Southern Appalachians, featuring diverse ecosystems from ridgetop meadows to creek-side hollows. The land includes extensive food forests, managed woodlands, seasonal creeks, and numerous micro-hydro sites along the South Fork of the Mills River.",
    aiConfidence: 0.93,
    sourcesCount: 15,
    isPublished: true,
    isFormingDisclaimer: false,
    tags: ["Permaculture", "Micro-Hydro", "Sociocracy", "Natural Building", "Food Forest", "Mushroom Cultivation"],
    links: [{ url: "https://www.earthaven.org", title: "Official Website", type: "website" }],
  },
  {
    name: "Auroville",
    slug: "auroville",
    tagline: "An international experimental township in Tamil Nadu, India dedicated to human unity and sustainable living",
    overview: "Auroville is a universal township in southern India, founded in 1968 by Mirra Alfassa (known as 'The Mother') with the endorsement of UNESCO. Spanning nearly 20 square kilometers, it is home to approximately 3,200 residents from over 60 countries, making it one of the largest and most diverse intentional communities in the world.\n\nThe township is organized around the Matrimandir, a golden meditation sphere at its center, surrounded by zones dedicated to international culture, industry, residential life, and a vast greenbelt. Auroville has pioneered reforestation of barren land, renewable energy adoption, and alternative education models on a scale unmatched by any other intentional community.",
    locationCountry: "India",
    locationRegion: "Tamil Nadu",
    locationLat: 12.01,
    locationLng: 79.81,
    stage: "mature",
    population: 3200,
    foundedYear: 1968,
    websiteUrl: "https://www.auroville.org",
    heroImageUrl: "/images/communities/auroville.png",
    solarpunkScore: 85,
    scoreEnergy: 8.5,
    scoreLand: 9.5,
    scoreTech: 8.0,
    scoreGovernance: 7.0,
    scoreCommunity: 9.0,
    scoreCircularity: 8.0,
    techStack: { energy: ["Solar Farms", "Wind Turbines", "Biogas Plants"], water: ["Rainwater Harvesting", "Water Recycling", "Check Dams"], food: ["Organic Farms", "Food Forests", "Seed Banks", "Aquaponics"], shelter: ["Compressed Earth Blocks", "Ferrocement", "Rammed Earth", "Bamboo Construction"], digital: ["Community Intranet", "GIS Mapping", "IoT Monitoring"], governance: ["Residents Assembly", "Working Groups", "Auroville Foundation"] },
    communityLife: "Auroville operates as an experimental township with no private property - all land belongs to the Auroville Foundation. Residents work in community-run units spanning education, healthcare, environmental restoration, and manufacturing. The economy is partially cashless within the township, with a community-run financial service handling internal transactions.\n\nCultural life is extraordinarily rich, with residents from over 60 nations sharing traditions, arts, and educational approaches. The community runs multiple schools, a university center, and hosts frequent cultural events and festivals.",
    howToJoin: "Joining Auroville involves a structured newcomer process. Visitors typically come for an initial stay of 2-4 weeks, followed by a longer volunteering period. The formal newcomer process takes about 2 years and involves integration into community work, housing, and governance.\n\nNewcomers contribute to a community fund and secure housing through the township's system. Auroville actively welcomes people from all nationalities and backgrounds.",
    landDescription: "Nearly 20 square kilometers of land in coastal Tamil Nadu, India. When founded, the area was barren eroded plateau. Through decades of reforestation, Auroville has planted over 3 million trees, creating a thriving tropical dry evergreen forest. The landscape includes organic farms, botanical gardens, canyons, and a dedicated greenbelt surrounding the township center.",
    aiConfidence: 0.97,
    sourcesCount: 25,
    isPublished: true,
    isFormingDisclaimer: false,
    tags: ["Reforestation", "Solar Energy", "International", "Alternative Education", "UNESCO", "Open Source"],
    links: [{ url: "https://www.auroville.org", title: "Official Website", type: "website" }],
  },
  {
    name: "Tamera Peace Research Village",
    slug: "tamera",
    tagline: "A peace research center and ecovillage in the Alentejo region of Portugal pioneering water retention landscapes",
    overview: "Tamera is a peace research and education center on 335 acres in the Alentejo region of Portugal, founded in 1995. What began as a small group of German peace activists has grown into a community of approximately 170 residents working on healing biotopes - model communities designed to demonstrate that peaceful coexistence between humans and nature is achievable at scale.\n\nTamera is perhaps best known for its groundbreaking Water Retention Landscape, designed by Austrian permaculture pioneer Sepp Holzer. The system of lakes and swales has transformed arid land into a productive landscape, serving as a model for large-scale ecosystem restoration in Mediterranean climates.",
    locationCountry: "Portugal",
    locationRegion: "Alentejo",
    locationLat: 37.75,
    locationLng: -8.53,
    stage: "established",
    population: 170,
    foundedYear: 1995,
    websiteUrl: "https://www.tamera.org",
    heroImageUrl: "/images/communities/tamera.png",
    solarpunkScore: 80,
    scoreEnergy: 9.0,
    scoreLand: 9.5,
    scoreTech: 7.5,
    scoreGovernance: 7.0,
    scoreCommunity: 7.5,
    scoreCircularity: 7.5,
    techStack: { energy: ["Solar Village", "Scheffler Mirrors (Concentrated Solar)", "Biogas"], water: ["Water Retention Landscape", "Lake Systems", "Swales"], food: ["Food Forest", "Vegetable Gardens", "Seed Saving"], shelter: ["Eco-Construction", "Solar Greenhouse"], digital: ["Community Internet"], governance: ["Forum Process", "Political Theory"] },
    communityLife: "Life at Tamera is centered around three pillars: ecology, community, and global peace work. Residents participate in daily communal life including shared meals, work in the various departments, and regular forums - a unique form of transparent communication practice developed by the community.\n\nTamera runs extensive education programs, hosting hundreds of visitors annually for courses on permaculture, peace studies, and community building. The community also maintains international partnerships with peace projects worldwide.",
    howToJoin: "Tamera offers various entry points: short visits, volunteer stays, and longer educational programs. Those interested in joining typically spend 1-2 years participating in community programs before being considered for long-term membership. The community is selective and focuses on attracting people committed to peace research.",
    landDescription: "335 acres of formerly degraded Mediterranean landscape in the Alentejo region of Portugal. Through the Water Retention Landscape, Tamera has created a chain of lakes and swales that have restored springs, rehydrated the land, and created a microclimate supporting diverse agriculture. The landscape now features food forests, gardens, and restored native vegetation.",
    aiConfidence: 0.92,
    sourcesCount: 14,
    isPublished: true,
    isFormingDisclaimer: false,
    tags: ["Water Retention", "Concentrated Solar", "Peace Research", "Permaculture", "Education Center"],
    links: [{ url: "https://www.tamera.org", title: "Official Website", type: "website" }],
  },
  {
    name: "Crystal Waters",
    slug: "crystal-waters",
    tagline: "Australia's first permaculture village, a pioneering eco-community in the Sunshine Coast hinterland",
    overview: "Crystal Waters is Australia's first purpose-designed permaculture village, established in 1988 on 640 acres in the Sunshine Coast hinterland of Queensland. The community was designed by permaculture co-originator Bill Mollison's associate Max Lindegger, making it a landmark in sustainable settlement design.\n\nWith approximately 250 residents across 85 residential lots, Crystal Waters demonstrates how thoughtful landscape design can create a productive, biodiverse, and socially vibrant community. The village has won the United Nations World Habitat Award and serves as a model for ecologically designed settlements worldwide.",
    locationCountry: "Australia",
    locationRegion: "Queensland",
    locationLat: -26.62,
    locationLng: 152.72,
    stage: "mature",
    population: 250,
    foundedYear: 1988,
    websiteUrl: "https://crystalwaters.org.au",
    heroImageUrl: "/images/communities/crystal-waters.png",
    solarpunkScore: 76,
    scoreEnergy: 7.5,
    scoreLand: 9.0,
    scoreTech: 6.0,
    scoreGovernance: 7.5,
    scoreCommunity: 8.0,
    scoreCircularity: 7.0,
    techStack: { energy: ["Solar PV", "Solar Hot Water"], water: ["Constructed Wetlands", "Reed Bed Systems", "Dam Water Storage"], food: ["Permaculture Food Forests", "Community Gardens", "Native Food Plants"], shelter: ["Passive Solar Design", "Rammed Earth"], digital: ["Broadband Internet"], governance: ["Body Corporate", "Community Association"] },
    communityLife: "Crystal Waters operates as a body corporate with individual lot ownership within a permaculture-designed landscape. Community life includes shared facilities like a community hall, swimming pool, cooperative store, and shared open spaces. Regular community events, markets, and work bees bring residents together.\n\nThe village supports multiple small businesses and cottage industries, and hosts permaculture courses and eco-tourism visitors. Residents range from young families to retirees, creating a diverse and multigenerational community.",
    howToJoin: "Joining Crystal Waters involves purchasing a residential lot or existing home within the village. Lot prices vary but are generally accessible compared to nearby coastal areas. New residents agree to the village's environmental covenants and body corporate rules.\n\nThe community welcomes visitors through its eco-tourism offerings and regular open days.",
    landDescription: "640 acres of undulating subtropical landscape in the Sunshine Coast hinterland. The land was designed using permaculture principles with residential clusters separated by productive landscapes, wildlife corridors, and extensive dam systems for water management. Native vegetation has been restored alongside productive food forests.",
    aiConfidence: 0.90,
    sourcesCount: 10,
    isPublished: true,
    isFormingDisclaimer: false,
    tags: ["Permaculture Village", "UN Habitat Award", "Solar Energy", "Constructed Wetlands", "Family-Friendly"],
    links: [{ url: "https://crystalwaters.org.au", title: "Official Website", type: "website" }],
  },
  {
    name: "Damanhur",
    slug: "damanhur",
    tagline: "A federation of spiritual communities in the foothills of the Italian Alps with underground temples and advanced eco-tech",
    overview: "Damanhur is a federation of spiritual communities and ecovillages in the Piedmont region of Italy, founded in 1975. With approximately 600 residents spread across multiple sites, Damanhur has grown into one of Europe's largest and most innovative intentional communities, recognized by the United Nations as a model for sustainable society.\n\nPerhaps most famously, Damanhur is home to the Temples of Humankind - an extraordinary underground complex of halls, corridors, and chambers carved into the mountain over decades, featuring stunning mosaics, sculptures, and stained glass. Beyond art, the community has developed sophisticated renewable energy systems and a complementary currency (the Credito) used within its internal economy.",
    locationCountry: "Italy",
    locationRegion: "Piedmont",
    locationLat: 45.41,
    locationLng: 7.62,
    stage: "mature",
    population: 600,
    foundedYear: 1975,
    websiteUrl: "https://www.damanhur.org",
    heroImageUrl: "/images/communities/damanhur.png",
    solarpunkScore: 74,
    scoreEnergy: 7.0,
    scoreLand: 6.5,
    scoreTech: 7.5,
    scoreGovernance: 8.0,
    scoreCommunity: 8.5,
    scoreCircularity: 7.0,
    techStack: { energy: ["Solar PV", "Geothermal Heating"], water: ["Water Recycling"], food: ["Organic Farms", "Community Gardens"], shelter: ["Eco-Renovation", "Underground Temple Complex"], digital: ["Community Intranet", "Complementary Currency System"], governance: ["Democratic Constitution", "Elected Government", "Complementary Currency (Credito)"] },
    communityLife: "Damanhur operates as a federation of smaller communities (called nucleos), each with 15-25 members. The federation has its own constitution, elected government, schools, and economic system including the Credito currency. Cultural life is rich with art, music, and spiritual practice central to daily life.\n\nThe community runs numerous enterprises from organic farming to technology development, and has an extensive education program for both residents and visitors. Damanhur is also known for its plant music research - using biosensors to translate plant bioelectrical signals into music.",
    howToJoin: "Damanhur welcomes visitors through its guest program and guided tours of the Temples of Humankind. Those interested in longer engagement can participate in study programs, temporary stays, and eventually apply for citizenship. The community has a structured pathway from visitor to citizen that typically takes 1-2 years.",
    landDescription: "Multiple sites across the alpine foothills of Piedmont, Italy. The primary community is located in the Valchiusella valley, featuring mountain terrain with forests, meadows, and the famous underground temple complex carved into the rock over decades of work.",
    aiConfidence: 0.91,
    sourcesCount: 13,
    isPublished: true,
    isFormingDisclaimer: false,
    tags: ["Underground Temples", "Complementary Currency", "Art Community", "Geothermal", "Federation Model"],
    links: [{ url: "https://www.damanhur.org", title: "Official Website", type: "website" }],
  },
  {
    name: "Findhorn Foundation",
    slug: "findhorn-foundation",
    tagline: "A pioneering spiritual and ecological community in northern Scotland with decades of sustainable innovation",
    overview: "The Findhorn Foundation is a spiritual community and eco-village in Moray, Scotland, founded in 1962. One of the oldest and most well-known intentional communities in the world, Findhorn has been at the forefront of ecological building, renewable energy, and holistic education for decades.\n\nThe community's ecological footprint is among the lowest measured in the industrialized world - roughly half the UK national average. Findhorn has developed innovative ecological housing, including some of the first large-scale passive solar buildings in Scotland, barrel houses made from recycled whisky barrels, and a community-owned wind park.",
    locationCountry: "Scotland",
    locationRegion: "Moray",
    locationLat: 57.66,
    locationLng: -3.61,
    stage: "mature",
    population: 350,
    foundedYear: 1962,
    websiteUrl: "https://www.findhorn.org",
    heroImageUrl: "/images/communities/findhorn.png",
    solarpunkScore: 81,
    scoreEnergy: 9.0,
    scoreLand: 7.5,
    scoreTech: 7.5,
    scoreGovernance: 8.0,
    scoreCommunity: 9.0,
    scoreCircularity: 7.5,
    techStack: { energy: ["Community Wind Park (4 turbines)", "Solar PV", "Biomass Heating"], water: ["Living Machine (Biological Wastewater Treatment)"], food: ["Organic Garden", "Community Supported Agriculture"], shelter: ["Passive Solar Housing", "Barrel Houses", "Eco-Homes"], digital: ["Community Internet", "Online Learning Platform"], governance: ["Spiritual Foundation Model", "Community Council"] },
    communityLife: "Findhorn operates as both a residential community and an international education center, hosting thousands of participants annually in programs on sustainability, personal development, and community building. Daily life combines work in community departments, spiritual practice, and communal gatherings.\n\nThe community includes people from over 40 countries, creating a vibrant multicultural environment. Residents work in the foundation's programs, businesses, and services, or pursue their own projects within the community.",
    howToJoin: "Findhorn offers multiple entry points: short workshops, a month-long Experience Week, and longer work-study programs. Long-term residency involves joining as a co-worker for a period before becoming a community member. The foundation also has a surrounding eco-village with individual homes and housing cooperatives.",
    landDescription: "The community occupies two main sites in Moray, Scotland: The Park (the original caravan site near Findhorn Bay) and Cluny Hill (a converted Victorian hotel). The Park campus features the ecological village with innovative housing, organic gardens, and the community wind park, all set in the sandy landscape of the Moray Firth coastline.",
    aiConfidence: 0.94,
    sourcesCount: 18,
    isPublished: true,
    isFormingDisclaimer: false,
    tags: ["Wind Energy", "Living Machine", "Education Center", "Spiritual Community", "Passive Solar", "International"],
    links: [{ url: "https://www.findhorn.org", title: "Official Website", type: "website" }],
  },
  {
    name: "Aardehuizen",
    slug: "aardehuizen",
    tagline: "A community of 23 earthship-inspired homes in the Netherlands demonstrating closed-loop living",
    overview: "Aardehuizen (Earth Houses) is a community of 23 earthship-inspired homes in Olst, Netherlands, completed in 2014. Drawing on Michael Reynolds' Earthship concept but adapted for the Dutch climate and building codes, this community demonstrates that self-sufficient housing can work even in northern European conditions.\n\nEach home is partially earth-sheltered with walls made from recycled materials including car tires, cans, and bottles. The homes incorporate integrated greenhouses, rainwater harvesting, and solar energy systems, creating a community that minimizes its environmental impact while maximizing comfort and resilience.",
    locationCountry: "Netherlands",
    locationRegion: "Olst",
    locationLat: 52.33,
    locationLng: 6.12,
    stage: "established",
    population: 60,
    foundedYear: 2014,
    websiteUrl: "https://www.aardehuizen.nl",
    heroImageUrl: "/images/communities/aardehuizen.png",
    solarpunkScore: 73,
    scoreEnergy: 8.0,
    scoreLand: 6.5,
    scoreTech: 8.0,
    scoreGovernance: 7.0,
    scoreCommunity: 7.0,
    scoreCircularity: 8.5,
    techStack: { energy: ["Solar PV", "Passive Solar (Integrated Greenhouses)"], water: ["Rainwater Harvesting", "Greywater Treatment Plants"], food: ["Integrated Greenhouses", "Community Garden"], shelter: ["Earthship-Inspired Design", "Recycled Materials (Tires, Cans, Glass Bottles)", "Earth-Sheltered"], digital: ["Smart Home Monitoring"], governance: ["Residents Association", "Consensus-Based"] },
    communityLife: "The Aardehuizen community functions as a neighborhood of individually owned but cooperatively planned earthship homes. Residents share common spaces, a community garden, and participate in regular community meetings and shared maintenance.\n\nThe community hosts educational tours and workshops, welcoming thousands of visitors annually who come to learn about earthship building and sustainable living in a northern climate.",
    howToJoin: "As a built-out community, joining Aardehuizen typically requires purchasing an existing home when one becomes available. The community maintains a waiting list for interested buyers. Prospective residents should align with the community's ecological values and participate in the residents' association.",
    landDescription: "A compact community site in Olst, Netherlands, featuring 23 earthship-inspired homes arranged in a deliberate pattern with shared green spaces, community gardens, and natural landscaping. The Dutch flatland setting is enhanced by the earth-sheltered design of the homes, which blend into the landscape.",
    aiConfidence: 0.88,
    sourcesCount: 8,
    isPublished: true,
    isFormingDisclaimer: false,
    tags: ["Earthship", "Recycled Materials", "Solar Energy", "Rainwater Harvesting", "Closed-Loop", "Visitors Welcome"],
    links: [{ url: "https://www.aardehuizen.nl", title: "Official Website", type: "website" }],
  },
  {
    name: "EcoVillage at Ithaca",
    slug: "ecovillage-at-ithaca",
    tagline: "A cohousing community in New York's Finger Lakes region integrating green building with academic research",
    overview: "EcoVillage at Ithaca (EVI) is a cohousing community located on 175 acres near Cornell University in Ithaca, New York. Founded in 1991, EVI consists of three cohousing neighborhoods - FROG (First Residents Group), SONG (Second Neighborhood Group), and TREE (Third Residential EcoVillage Experience) - each with about 30 homes arranged around common facilities.\n\nEVI is notable for its integration of academic research with community living. Its proximity to Cornell University has made it a living laboratory for sustainable design, with studies on everything from energy performance to social dynamics conducted on-site. The community has preserved 80% of its land as open space, including organic farmland, forests, and wetlands.",
    locationCountry: "United States",
    locationRegion: "New York",
    locationLat: 42.43,
    locationLng: -76.54,
    stage: "mature",
    population: 225,
    foundedYear: 1991,
    websiteUrl: "https://ecovillageithaca.org",
    heroImageUrl: "/images/communities/ecovillage-ithaca.png",
    solarpunkScore: 72,
    scoreEnergy: 7.0,
    scoreLand: 7.5,
    scoreTech: 6.5,
    scoreGovernance: 8.0,
    scoreCommunity: 8.5,
    scoreCircularity: 6.0,
    techStack: { energy: ["Solar PV Arrays", "Superinsulated Homes", "Net-Zero Design"], water: ["Constructed Wetlands"], food: ["Organic Farm (West Haven Farm)", "CSA Program"], shelter: ["Passive Solar Cohousing", "High-Performance Building Envelopes"], digital: ["Community Intranet"], governance: ["Neighborhood Meetings", "Community-Wide Governance", "Cooperative Model"] },
    communityLife: "EVI's three neighborhoods each have their own common house with a large kitchen, dining room, and shared facilities. Residents regularly share meals, with each neighborhood cooking communal dinners several times per week. The community maintains extensive organic farmland through West Haven Farm, which operates a CSA and farm stand.\n\nThe community is deeply connected to the broader Ithaca area, with residents active in local politics, education, and environmental advocacy.",
    howToJoin: "Joining EVI involves purchasing a home in one of the three neighborhoods when available. The community maintains a waitlist and prospective residents are encouraged to visit and participate in community events before purchasing. The cohousing model means residents own their individual units while sharing common spaces.",
    landDescription: "175 acres in the Finger Lakes region of New York, with 80% preserved as open space. The land features three cohousing clusters, West Haven organic farm, forest trails, ponds, wetlands, and extensive meadows. The property sits on a hillside with views of the surrounding countryside.",
    aiConfidence: 0.91,
    sourcesCount: 11,
    isPublished: true,
    isFormingDisclaimer: false,
    tags: ["Cohousing", "Organic Farm", "Academic Research", "Net-Zero", "CSA Program", "Family-Friendly"],
    links: [{ url: "https://ecovillageithaca.org", title: "Official Website", type: "website" }],
  },
  {
    name: "Twin Oaks Community",
    slug: "twin-oaks",
    tagline: "An egalitarian income-sharing community in rural Virginia with 55+ years of cooperative living",
    overview: "Twin Oaks is one of the longest-running secular intentional communities in the United States, founded in 1967 on 450 acres in rural Virginia. With approximately 90 adult members and 15 children, the community operates on principles of cooperation, egalitarianism, and sustainability.\n\nWhat makes Twin Oaks distinctive is its income-sharing economy: all income from community businesses (hammock manufacturing, tofu production, book indexing, and seed growing) is shared equally among members, who each contribute a labor quota of about 42 hours per week in exchange for having all needs met - housing, food, healthcare, and a small personal spending allowance.",
    locationCountry: "United States",
    locationRegion: "Virginia",
    locationLat: 37.93,
    locationLng: -78.10,
    stage: "mature",
    population: 90,
    foundedYear: 1967,
    websiteUrl: "https://www.twinoaks.org",
    heroImageUrl: "/images/communities/twin-oaks.png",
    solarpunkScore: 71,
    scoreEnergy: 6.0,
    scoreLand: 7.5,
    scoreTech: 5.5,
    scoreGovernance: 8.5,
    scoreCommunity: 9.0,
    scoreCircularity: 7.0,
    techStack: { energy: ["Solar PV (Growing)", "Wood Heat"], water: ["Well Water", "Greywater Systems"], food: ["Organic Gardens", "Dairy Goats", "Seed Business"], shelter: ["Renovated Farm Buildings", "New Green Construction"], digital: ["Shared Computing Resources"], governance: ["Planner-Manager System", "Behavior Code", "Egalitarian Labor System"] },
    communityLife: "Life at Twin Oaks revolves around the labor system. Members choose from a variety of work areas including hammock weaving, tofu making, cooking, gardening, childcare, maintenance, and administration. The community provides all basic needs plus healthcare, and members receive a small weekly personal spending allowance.\n\nSocial life is rich with shared meals, parties, seasonal celebrations, and a strong culture of cooperation and mutual aid. The community produces most of its own food and emphasizes self-sufficiency.",
    howToJoin: "Twin Oaks has a well-defined visitor program and membership process. Prospective members visit for three weeks, after which they can apply for provisional membership (lasting about a year). Full membership is granted through community approval.\n\nJoining requires no financial buy-in - members contribute their labor and share in the community's resources equally. The community actively recruits new members.",
    landDescription: "450 acres of rolling Virginia countryside featuring mixed forests, organic gardens, pastures for dairy goats, a swimming pond, and various work buildings. The community has expanded and improved its infrastructure over five decades, creating a well-established homestead with numerous buildings and productive landscapes.",
    aiConfidence: 0.94,
    sourcesCount: 16,
    isPublished: true,
    isFormingDisclaimer: false,
    tags: ["Income-Sharing", "Egalitarian", "Hammock Manufacturing", "Organic Gardens", "Accepting Members", "Visitors Welcome"],
    links: [{ url: "https://www.twinoaks.org", title: "Official Website", type: "website" }],
  },
  {
    name: "Breitenbush Hot Springs",
    slug: "breitenbush-hot-springs",
    tagline: "A worker-owned cooperative retreat center and intentional community surrounded by old-growth forest in Oregon",
    overview: "Breitenbush Hot Springs is a worker-owned cooperative and intentional community located in the Cascade Range of Oregon, surrounded by old-growth forest and natural hot springs. Founded as a cooperative in 1977, Breitenbush serves as both a retreat center and a residential community for approximately 60 worker-owners and their families.\n\nThe community has pioneered geothermal energy use, tapping the natural hot springs not only for the famous soaking pools but also for heating all buildings on the property. Combined with micro-hydro power from the Breitenbush River, the community generates nearly all its energy from renewable sources.",
    locationCountry: "United States",
    locationRegion: "Oregon",
    locationLat: 44.78,
    locationLng: -121.97,
    stage: "mature",
    population: 60,
    foundedYear: 1977,
    websiteUrl: "https://breitenbush.com",
    heroImageUrl: "/images/communities/breitenbush.png",
    solarpunkScore: 77,
    scoreEnergy: 9.5,
    scoreLand: 8.0,
    scoreTech: 6.5,
    scoreGovernance: 8.0,
    scoreCommunity: 7.5,
    scoreCircularity: 7.0,
    techStack: { energy: ["Geothermal Heating", "Micro-Hydro Power", "Natural Hot Springs"], water: ["Mountain Spring Water", "Hot Springs Systems"], food: ["Organic Kitchen Garden", "Vegetarian Cuisine Program"], shelter: ["Geothermally Heated Cabins", "Sustainable Forest Lodging"], digital: ["Limited (Intentional Digital Detox Zone)"], governance: ["Worker-Owned Cooperative", "Consensus Decision-Making"] },
    communityLife: "As a worker-owned cooperative, all community members are also employees of the retreat center. Work includes maintaining the hot springs facilities, preparing organic vegetarian meals for guests, leading wellness programs, and stewarding the surrounding old-growth forest.\n\nThe community culture emphasizes connection with nature, wellness, and cooperative economics. Daily life integrates work, soaking in hot springs, and community gatherings in a spectacular natural setting.",
    howToJoin: "Joining Breitenbush involves applying for employment with the cooperative. Worker-owners live on-site and participate in all aspects of community governance. Positions open periodically and require a commitment to cooperative principles and sustainable living.\n\nThe community also offers seasonal and volunteer positions for those wanting to experience the lifestyle before committing.",
    landDescription: "154 acres of old-growth forest along the Breitenbush River in the Cascade Range, featuring multiple natural hot springs, meadows, and riverside habitats. The community sits at about 2,000 feet elevation, surrounded by the Willamette National Forest with access to mountain trails, rivers, and wilderness.",
    aiConfidence: 0.89,
    sourcesCount: 9,
    isPublished: true,
    isFormingDisclaimer: false,
    tags: ["Geothermal", "Hot Springs", "Worker Cooperative", "Old-Growth Forest", "Micro-Hydro", "Retreat Center"],
    links: [{ url: "https://breitenbush.com", title: "Official Website", type: "website" }],
  },
  {
    name: "Freedom Cove",
    slug: "freedom-cove",
    tagline: "A floating self-sufficient homestead on the west coast of Vancouver Island, built entirely by hand over 30 years",
    overview: "Freedom Cove is a remarkable floating homestead in Cypress Bay, off the west coast of Vancouver Island, British Columbia. Built entirely by hand over 30+ years by artists Wayne Adams and Catherine King, this self-sufficient floating village spans 12 interconnected platforms including a house, art studios, a dance floor, gardens, and a lighthouse.\n\nThe homestead generates its own electricity through solar panels and a small generator, grows food in floating gardens, and collects rainwater for freshwater. Though not a traditional intentional community, Freedom Cove represents one of the most visually stunning examples of individual solarpunk ingenuity and off-grid innovation.",
    locationCountry: "Canada",
    locationRegion: "British Columbia",
    locationLat: 49.32,
    locationLng: -126.05,
    stage: "established",
    population: 2,
    foundedYear: 1992,
    websiteUrl: "https://freedomcove.ca",
    heroImageUrl: "/images/communities/freedom-cove.png",
    solarpunkScore: 68,
    scoreEnergy: 7.0,
    scoreLand: 6.0,
    scoreTech: 7.5,
    scoreGovernance: 5.0,
    scoreCommunity: 5.0,
    scoreCircularity: 8.5,
    techStack: { energy: ["Solar Panels", "Small Generator (Backup)"], water: ["Rainwater Collection", "Water Storage Tanks"], food: ["Floating Gardens", "Greenhouse", "Fishing"], shelter: ["Hand-Built Floating Platforms", "Recycled Materials", "Driftwood Construction"], digital: ["Satellite Internet"], governance: ["Individual Homestead"] },
    communityLife: "Freedom Cove is a two-person homestead rather than a traditional community, but it has become an inspiration and educational destination for thousands of visitors who arrive by boat each summer. Wayne and Catherine live a fully self-sufficient lifestyle, growing food in floating gardens, creating art, and maintaining their extraordinary hand-built home.\n\nThe couple welcomes visitors during summer months, sharing their knowledge of off-grid living and sustainable construction.",
    howToJoin: "Freedom Cove is a private homestead and not accepting new members. However, visitors can arrange tours during the summer season by contacting Wayne and Catherine. The homestead serves as an inspiration and learning opportunity rather than a joinable community.",
    landDescription: "A floating compound of 12 interconnected platforms in Cypress Bay, accessed only by boat. The 'land' includes living quarters, art studios, greenhouses, a dance floor, a candle-making workshop, and extensive floating gardens. Surrounded by the pristine waters and old-growth forests of Vancouver Island's west coast.",
    aiConfidence: 0.85,
    sourcesCount: 7,
    isPublished: true,
    isFormingDisclaimer: false,
    tags: ["Floating Homestead", "Solar Energy", "Self-Sufficient", "Recycled Materials", "Art", "Off-Grid"],
    links: [{ url: "https://freedomcove.ca", title: "Official Website", type: "website" }],
  },
  {
    name: "Acorn Land Labs",
    slug: "acorn-land-labs",
    tagline: "A tech-forward regenerative land project in Colorado merging precision agriculture with community building",
    overview: "Acorn Land Labs is a forming regenerative community and research project in Colorado, focused on merging modern technology with regenerative land stewardship. The project uses drone mapping, IoT soil sensors, precision agriculture tools, and open-source hardware to optimize land restoration and food production.\n\nStill in early stages, Acorn Land Labs represents the cutting edge of tech-enabled regenerative communities, attracting engineers, permaculturists, and systems thinkers who want to prove that technology and ecology can be deeply complementary rather than opposed.",
    locationCountry: "United States",
    locationRegion: "Colorado",
    locationLat: 39.55,
    locationLng: -104.97,
    stage: "forming",
    population: 8,
    foundedYear: 2021,
    websiteUrl: "https://acornlandlabs.com",
    heroImageUrl: "/images/communities/acorn-land-labs.png",
    solarpunkScore: 65,
    scoreEnergy: 6.0,
    scoreLand: 7.0,
    scoreTech: 9.5,
    scoreGovernance: 6.0,
    scoreCommunity: 5.5,
    scoreCircularity: 5.5,
    techStack: { energy: ["Solar Array (Planned)"], water: ["IoT Soil Moisture Sensors", "Drip Irrigation Automation"], food: ["Precision Agriculture", "Drone-Mapped Food Forest (Planned)"], shelter: ["Modular Construction"], digital: ["IoT Sensor Network", "Drone Mapping", "Open-Source Land Management Platform", "GIS Analysis"], governance: ["DAO-Inspired Governance (In Development)"] },
    communityLife: "As a forming community, daily life at Acorn Land Labs is focused on land development, technology deployment, and community formation. The small founding team works on installing sensor networks, developing open-source land management software, and building relationships with the broader regenerative technology community.\n\nThe project hosts hack days and workshops bringing together technologists and land stewards to collaborate on tools for regenerative land management.",
    howToJoin: "Acorn Land Labs is actively seeking founding members, particularly those with skills in software engineering, permaculture design, electronics/IoT, or community building. Interested individuals can reach out through the website to discuss involvement in the project.",
    landDescription: "A growing land parcel in Colorado where the team is implementing precision agriculture and regenerative land management using technology-driven approaches. The project is still acquiring and developing land, with plans for food forests, sensor-monitored soil zones, and experimental growing areas.",
    aiConfidence: 0.72,
    sourcesCount: 5,
    isPublished: true,
    isFormingDisclaimer: true,
    tags: ["IoT Sensors", "Drone Mapping", "Precision Agriculture", "Open Source", "DAO Governance", "Accepting Members"],
    links: [{ url: "https://acornlandlabs.com", title: "Official Website", type: "website" }],
  },
  {
    name: "Solar Punk Farms",
    slug: "solar-punk-farms",
    tagline: "A regenerative micro-farm network using solar-powered automation and community-supported agriculture",
    overview: "Solar Punk Farms is an emerging network of regenerative micro-farms that combine solar-powered automation, open-source agricultural robotics, and community-supported agriculture (CSA) models. The project aims to prove that small-scale farming can be economically viable when augmented with appropriate technology.\n\nThe project experiments with solar-powered irrigation systems, automated composting, sensor-monitored growing conditions, and AI-assisted crop planning. While still in early stages, Solar Punk Farms has attracted attention for its innovative approach to making small-scale regenerative farming accessible and replicable.",
    locationCountry: "United States",
    locationRegion: "Midwest",
    locationLat: 41.88,
    locationLng: -87.63,
    stage: "forming",
    population: 5,
    foundedYear: 2022,
    websiteUrl: "https://solarpunkfarms.org",
    heroImageUrl: "/images/communities/solar-punk-farms.png",
    solarpunkScore: 58,
    scoreEnergy: 7.5,
    scoreLand: 6.0,
    scoreTech: 8.0,
    scoreGovernance: 5.0,
    scoreCommunity: 4.5,
    scoreCircularity: 5.5,
    techStack: { energy: ["Solar-Powered Irrigation", "Solar Panel Array"], water: ["Automated Drip Irrigation", "Rain Barrel Collection"], food: ["Regenerative Micro-Farming", "AI Crop Planning", "Automated Composting"], shelter: ["Shipping Container Greenhouse"], digital: ["Open-Source Farm Robotics", "Sensor Network", "Farm Management Software"], governance: ["Cooperative Model (Forming)"] },
    communityLife: "Solar Punk Farms is still forming its community identity. Current activities center around technology development, farm operations, and outreach. The small team hosts volunteer work days, farm tours, and technology demonstrations to build a broader community of supporters and potential members.",
    howToJoin: "Solar Punk Farms welcomes volunteers, technologists, and aspiring regenerative farmers. The project is open to new members who can contribute skills in farming, technology, or community organizing. Contact through their website for current opportunities.",
    landDescription: "Operating on leased micro-farm plots, Solar Punk Farms is developing a model that can be replicated across multiple small parcels. Current operations include greenhouse growing, open-field regenerative plots, and technology testing areas with sensor networks and solar-powered equipment.",
    aiConfidence: 0.68,
    sourcesCount: 4,
    isPublished: true,
    isFormingDisclaimer: true,
    tags: ["Solar-Powered", "Farm Robotics", "CSA Model", "Open Source", "AI Agriculture", "Accepting Members"],
    links: [{ url: "https://solarpunkfarms.org", title: "Official Website", type: "website" }],
  },
  {
    name: "Kirra Community",
    slug: "kirra-community",
    tagline: "An eco-community project on the Gold Coast hinterland integrating permaculture design with smart home technology",
    overview: "Kirra Community is an eco-village project in the Gold Coast hinterland of Australia, blending permaculture landscape design with smart home technology and community-scale renewable energy. The project aims to create a model for suburban-density sustainable living that doesn't sacrifice modern comforts.\n\nThe community emphasizes that sustainability shouldn't mean going backward in comfort or convenience, instead leveraging technology to make regenerative living easier and more appealing to mainstream families.",
    locationCountry: "Australia",
    locationRegion: "Gold Coast",
    locationLat: -28.17,
    locationLng: 153.37,
    stage: "forming",
    population: 12,
    foundedYear: 2023,
    websiteUrl: "https://kirracommunity.com.au",
    heroImageUrl: "/images/communities/kirra.png",
    solarpunkScore: 55,
    scoreEnergy: 7.0,
    scoreLand: 5.5,
    scoreTech: 7.5,
    scoreGovernance: 5.0,
    scoreCommunity: 4.5,
    scoreCircularity: 5.0,
    techStack: { energy: ["Community Solar Array", "Battery Storage"], water: ["Smart Water Monitoring", "Rainwater Tanks"], food: ["Permaculture Food Forest (Design Phase)"], shelter: ["Smart Home Integration", "Passive Design"], digital: ["Smart Home Hub", "Community Dashboard", "Energy Monitoring"], governance: ["Strata Model with Eco-Covenants"] },
    communityLife: "Kirra Community is in its design and formation phase. The founding group meets regularly to refine the vision, engage with local councils, and develop the master plan. Community building activities include shared meals, permaculture workshops, and design charrettes.",
    howToJoin: "Kirra Community is actively seeking founding members and investors. The project offers information sessions and site visits for interested families and individuals. Financial contributions and skill-based participation opportunities are available.",
    landDescription: "A site in the Gold Coast hinterland of Queensland, Australia, featuring subtropical landscape with potential for diverse food production, native habitat restoration, and community-scale renewable energy generation.",
    aiConfidence: 0.65,
    sourcesCount: 3,
    isPublished: true,
    isFormingDisclaimer: true,
    tags: ["Smart Home", "Community Solar", "Permaculture", "Family-Friendly", "Accepting Members"],
    links: [{ url: "https://kirracommunity.com.au", title: "Official Website", type: "website" }],
  },
];

export async function seedCommunities() {
  const existingCount = await storage.getCommunityCount();
  if (existingCount > 0) {
    console.log(`Database already has ${existingCount} communities, skipping seed.`);
    return;
  }

  console.log("Seeding database with community data...");

  for (const seed of SEED_COMMUNITIES) {
    const { tags, links, ...communityData } = seed;

    const community = await storage.createCommunity({
      ...communityData,
      lastResearchedAt: new Date(),
      lastRefreshedAt: new Date(),
    });

    if (tags && tags.length > 0) {
      await storage.addTags(community.id, tags);
    }

    if (links && links.length > 0) {
      await storage.addLinks(community.id, links);
    }

    console.log(`  Seeded: ${community.name}`);
  }

  console.log(`Seeded ${SEED_COMMUNITIES.length} communities.`);
}
